version: '3.8'

services:
  db:
    image: postgres:15
    container_name: chronoscope_db
    restart: always
    environment:
      POSTGRES_USER: chronoscope
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: chronoscope
    ports:
      - "5433:5432"
    volumes:
      - chronoscope_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: chronoscope_redis
    restart: always
    ports:
      - "6380:6379"

volumes:
  chronoscope_pgdata:
